# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

---

#Ingress route for the genaidecoy service
{{- if eq .Values.genAIDecoyProtocol "http" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{.Values.genAIDecoyProtocol}}-genaidecoyingressroute
  namespace: default

spec:
  entryPoints:
    - websecure

  routes:
  - match: {{.Values.Pathprefix}}
    priority: {{.Values.priority}}
    kind: Rule
    services:
    - name: {{.Values.genAIDecoyProtocol}}-genaidecoy-service
      port: {{.Values.containerPort}}
{{- end }}

{{- if eq .Values.genAIDecoyProtocol "ssh" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{.Values.genAIDecoyProtocol}}-genaidecoyingressroute
  namespace: default

spec:
  entryPoints:
    - tcpep

  routes:
  - match: HostSNI(`*`)
    services:
      - name: {{.Values.genAIDecoyProtocol}}-genaidecoy-service
        port: {{.Values.containerPort}}
  tls: {}
    # secretName: my-tls-secret
    # options:
    #   name: default
    #   namespace: ""
{{- end }}