# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

---

#Ingress route for the genaidecoy service
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: genaidecoyingressroute
  namespace: default

spec:
  entryPoints:
    - websecure

  routes:
  - match: {{.Values.Pathprefix}}
    priority: {{.Values.priority}}
    kind: Rule
    services:
    - name: genaidecoy-service
      port: 8000