# Default values for genAIDecoy.

replicaCount: 1

imagereference: "crowsi/genaidecoy:0.1.0" #if you refer to a private repository, make sure to also specify the value "imagePullSecret"

containerPort: 8000

genAIApiKeyEnvVariableName: "GENAI_API_KEY"

useSecretProvider: true # Set to false to use a plain Kubernetes Secret
secretProvider: "genaidecoy-secret-provider"
secretKeyRefName: "AIapi-secret"
secretKeyRefKey: "genAIApiKey"

Pathprefix: "PathPrefix(`/api`)"

priority: 2





