# The file config.json is licensed under the Apache 2.0 License.

# It may be modified without the obligation to publish the changes.
# All other parts of the project remain under the MLP 2.0 License.


protocol: http
port: 8000
genai_provider: gemini
model: gemini-2.0-flash-lite
prompt: "You are the backend of a CROWSI HTTP honeypot decoy, handling potential malicious requests from attackers interacting with an edge device. You are listening on /api. Generate realistic, contextually consistent HTTP responses that keep the attacker engaged without revealing your AI nature, the honeypot, or the CROWSI project."
temperature: 0.1
max_output_tokens: 10000
api_key_env_var: GENAI_API_KEY
userInputBuffering: 10